### ISSUE TITLE
try...catch捕获不到SDK与节点网络连接异常产生的错误

### ISSUE THREAD

**Issue by tom112233** [FISCO-BCOS/nodejs-sdk#105]
在使用try…catch尝试捕获由于网络原因导致SDK和节点网络中断产生的错误时，上层应用因为捕获不到socket产生的错误而中断退出。例如：
```
try {
    // 查询区块高度
    return await web3jService.getBlockNumber();
  } catch (e) {
    // 捕获不到错误
    console.log(e);
  }
```
原因是：在channelPromise方法中，promise在socket报错前就返回给上层调用，导致后续产生的错误无法捕获。
解决方法：将报错放在Promise中，使用reject返回报错信息：
```
tlsSocket.on('error', function (error) {
    clear();
    reject(new NetworkError(error)) ;
});
```

**Comment by vita-dounai** [comment]
谢谢，一个非常有意思的问题！但是要解决这个问题，我认为还需要更深入一点讨论Node.js的异常机制和Node.js SDK的设计。

1. 为了尽可能复用socket，避免不必要的创建socket的开销，`channelPromise.js`中将用于网络通信的socket定义为了全局对象（确切的说是具有模块作用域的静态对象，还不是真正意义上的global对象，不过姑且先这么叫吧: )），参见：https://github.com/FISCO-BCOS/nodejs-sdk/blob/f8c53f36c4d8b904dba9d682d9dd1ab2d2eecacc/packages/api/common/network/channelPromise.js#L31
2. 当你在代码中使用try...catch时，实际的作用范围就只限于try...catch所包含的语句所处的栈帧，对于当前栈之外的地方发生异常是无能为力的。遗憾的是，socket作为全局对象，其生命周期的管理正是位于当前栈之外的，因此你此处的try...catch自然是捕获不到socket抛出的`NetworkError`异常的；
3. 如果一定要捕获这个异常怎么办？你给出的解决方案是一个思路，但是我认为这个方案还有点缺憾。假如`return await web3jService.getBlockNumber();`这句正常执行了（此时网络还没有异常），函数正常return回上一层，但是紧接着网络出现异常，此时我仍为你仍然没有办法捕获到这个异常，毕竟你的try...catch所在的函数都已经执行结束了。因此我认为通过一个local对象来承载global对象产生的异常并不是一个特别好的idea；
4. 那如何彻底解决这个问题？在最外层套一个大的try...catch显然不是一个好主意，不仅影响性能，而且依然没啥卵用（参考第2点）。所幸，Node.js自身提供了一些机制来帮助我们一定程度上避免“异常抓不住进程直接死”的问题：
    (1) 监听`process`的`uncaughtException`事件；
    (2) 使用Node.js自带的`domain`的模块，让函数运行在`domain`模块创建出的上下文环境中，并监听其`error`事件。

    这两种方式都有弊端，具体你可以查阅一下相关资料。一言以概之，当出现uncaught exception时，实际上进程的环境已经被部分破坏了，甚至还可能会出现内存泄漏的问题，因此不应该通过这两种方式让进程继续运行下去，而是优雅退出后迅速重启以免丧失服务能力，同时，服务最好有多个实例，这些功能可以直接使用`pm2`等工具方便地实现。

5. 最后还想讨论一个问题，socket异常时真的需要抛出个异常把自己干掉么？当初我在设计Node.js SDK时，觉得网络连接中断是个比较严重的系统问题，所以使用了这种非常暴力的方式。但是现在想来，实际应用中网络抖动应该是比较常见的问题，如果节点只是短暂失联的话就如此大动干戈是否值得？或许在之后的版本中会让socket断连时不抛出异常而是触发`process`的warning事件，并通过channel_promise抛出超时异常，使得上层能够轻易捕获并自行决定如何处理。

我只是一个Node.js的菜鸟，上面的看法如果有误或者你有更好的建议，欢迎回复讨论。

**Comment by tom112233** [comment]
谢谢回复，对于设计上尽可能的复用Socket以避免额外开销这一点非常同意。以下提出一些在这个问题上的个人处理方法进行讨论。
1.  socket对象作为模块内的单例静态对象，其产生错误事件后生成了Error对象，如果直接throw显然这一错误不能够被正常捕捉，只能通过你提到的第4点钟的两个方法处理。这两种方法由于产生了不确定性我不倾向于如此解决，尤其是在生产环境中，由于各种网络问题导致进程频繁重启是不可接受的。
2. 对于我提供的思路我是如何理解的？我认为使用Promise对象的reject将错误对象暴露出来的过程应该理解为**通过动态方法将错误信息捕获并抛出**。实际上，每一次调用channelPromise时，不论socket是新建的或是复用的，作为一个容器，一个新的Promise都会被生成，负责将socket本次调用的所有结果返回到外部世界（即上层调用），不论其是成功还是失败。因此：
    1. 在一次调用内，调用成功和错误的性质并无不同，其差异在于一旦出错我们可能需要作出额外的操作（比如删除socket等）。
    2. 我认为生成的Promise的`用于承载一个由global对象产生的错误的对象`这一定位言重了。其不涉及到错误的具体处理，仅仅是通知当前调用socket的请求发生了什么错误。对于错误本身的处理不会放到上一层进行，而是在错误监听器中调用其他方法统一处理，例如clear函数。这些处理函数属于全局处理的一部分，可以使socket在处理完成后达到可控制的预设状态（如：重试、断开连接等操作），只有在所有处理完成后reject才会带着错误信息返回上层，充当一个信使的作用。因此，Promise对象用于通知上层调用发生的错误是合适的。
3. 基于实例进一步讨论。对于你提出的假设`假如return await web3jService.getBlockNumber();第一次执行正常，之后网络出错抛出的异常无法捕获`。我进行了复现，复现方式为：
    1. 运行FIsco所有网络节点并正常请求一次（请求成功）
    2. 之后将所有Fisco节点关闭后请求一次（报错 链接被拒绝）
    3. 之后重新运行节点后请求一次 （请求成功）
以上过程node.js进程持续运行没有重启，所有错误行为都使用try..catch语法捕获。以下是对目前定义的两种错误监听器行为分析：
    - 对于error错误，即socket抛出的错误。我在步骤2时如预期捕获到了由error抛出的错误。这一请求的通过channelPromise获得了一个Promise并订阅接收到了Promise中包含的reject信息。
    - 对于end错误。由于请求已经结束，在` newSocket.on('end', () => {})`回调中我看到了连接中断的错误信息，但在当前进程内没有捕获到任何错误信息.(这一点暂时没有理解其原理，猜测是由于reject作为Promise回调函数的参数，由于Promise对象没有被监听，其reject虽然成功获取到信息但Promise被当做无引用对象被垃圾处理掉了)
    - 对于整个复现过程，每一次请求都拥有个独立的生命周期，在Promise成功返回正确数据或错误后结束。end事件发生时，不在任何一个调用的生命周期中，因此在这时，socket的状态对任何外部调用都是没有意义的，其出错也不需要返回到上层，在这里对socket进行相应处理即可（如删除socket、重试等）。只有下一个请求调用socket时，请求才会了解到socket需要重新建立，其行为将按照socket当前状态（重试、未连接等）独立处理。
4. 观察到channelPromise是根据检测sockets中是否包含指定socketID映射的socket对象来实现socket单例的，而这一对象仅在channelPromise中进行复用。因此，对全局socket的操作不涉及到其他模块和方法。将socket对象的单例创建方法放在Promise中理论上应该对性能的影响可以忽略不计，因为这时Promise仍然在准备参数的过程中，并没有创建Promise对象。
5. 对于你提到的第5点讨论，我同意只要捕获到错误就干掉自己是很粗暴的方式。我建议可以考虑加入一定的重连机制，即当一个调用在socket连接时捕获到某些类型的错误时（比如网络问题，节点掉线等），可以加入几轮重试后再考虑删除socket。重连的时间间隔、最大重连时间等常见设置可以加入到配置文件中由开发者自行决定。

以下为修改后的channelPromise供参考：
```
function channelPromise(data, type, node, authentication, timeout = null) {
    let ip = node.ip;
    let port = node.port;

    let socketID = `${ip}:${port}`;

    return new Promise(async (resolve, reject) => {

        if (!sockets.has(socketID)) {
            let newSocket = createNewSocket(ip, port, authentication);
            newSocket.unref();
            sockets.set(socketID, newSocket);

            let clear = () => {
                buffers.delete(socketID);
                lastBytesRead.delete(socketID);
                sockets.delete(socketID);
            };

            newSocket.on('error', function (error) {
                clear();
                // do something like retry, etc.
                // throw new NetworkError(error);
                reject(new NetworkError(error));
            });

            newSocket.on('end', () => {
                clear();
                reject(new NetworkError('disconnected from remote node'));
                // throw new NetworkError('disconnected from remote node');
            });
        }
        let tlsSocket = sockets.get(socketID);

        let dataPackage = data;
        if (type) {
            dataPackage = packData(JSON.stringify(data), type);
        }
        let uuid = dataPackage.uuid;

        tlsSocket.socketID = uuid;
        let packagedData = dataPackage.packagedData;
        if (timeout) {
            let eventEmitter = new events.EventEmitter();

            if (type === MESSAGE_TYPE.QUERY || type === MESSAGE_TYPE.CHANNEL_RPC_REQUEST) {
                Object.defineProperty(eventEmitter, 'readOnly', {
                    value: type === MESSAGE_TYPE.QUERY ? true : false,
                    writable: false,
                    configurable: false,
                    enumerable: false
                });
            }

            eventEmitter.on('gotresult', (result) => {
                clearContext(uuid);
                if (result.error) {
                    reject(result);
                } else {
                    resolve(result);
                }
                return; // This `return` is not necessary, but it may can avoid future trap
            });

            emitters.set(uuid, {
                emitter: eventEmitter
            });


            eventEmitter.on('timeout', () => {
                clearContext(uuid);
                reject({
                    'error': `timeout when send request:  ${JSON.stringify(data)}`
                });
                return; // This `return` is not necessary, but it may can avoid future trap
            });

            emitters.get(uuid).timer = setTimeout(() => {
                eventEmitter.emit('timeout');
            }, timeout);

            tlsSocket.write(packagedData);
        } else {
            tlsSocket.write(packagedData);
            resolve();
        }
    });
}
```

非常希望能够就这一问题进行广泛的讨论，期待您能够尽快回复，同时能够尽快地更好地解决这一问题。

**Comment by vita-dounai** [comment]
谢谢，是我对你之前描述的问题理解有误，欢迎把你修复后的代码以PR的形式贡献出来^_^
