### ISSUE TITLE
nodejs-sdk-api如何调用call?

### ISSUE THREAD

**Issue by DevinLin01** [FISCO-BCOS/nodejs-sdk#119]
`
async function call(){
    let res = await api.call('0x62195d0f77f66c445c4878b845f55d266875705d',{'func':'get()'},[])
    console.log(res)
}
`

solidity代码：
`pragma solidity ^0.4.23;

contract HelloWorldV4 {
    string name;

    constructor() public {
        name = "Hello, World!";
    }

    function get() public view returns (string) {
        return name;
    }

    function set(string n) public {
        name = n;
    }
}
`
![image](https://user-images.githubusercontent.com/32610116/117783977-a4c19580-b275-11eb-99b6-6bea07d46562.png)

**Comment by vita-dounai** [comment]
提示里面表示提供的ABI格式不正确，`call`的第二个参数是函数的 ABI 描述，类型是一个 Object，直接从 ABI 文件中复制然后用 JSON.parse 解析成对象就好了。
