### ISSUE TITLE
Node.js  SDK 如何创建账户？

### ISSUE THREAD

**Issue by tumobi** [FISCO-BCOS/nodejs-sdk#120]
在业务系统中，有新用户注册时，需要生成一个 fisco 账户，请问如何使用 node.js 生成？

**Comment by DevinLin01** [comment]
同问！！

**Comment by vita-dounai** [comment]
目前暂时没有提供相应的API，但是FISCO BCOS 官方提供一个叫get_account.sh的脚本可以生成账户，用 child_process 之类的手段启动这个脚本，就可以用于生成账户。
