### ISSUE TITLE
/usr/bin/env: "node\r": 没有那个文件或目录

### ISSUE THREAD

**Issue by DanielXuuuuu** [FISCO-BCOS/nodejs-sdk#42]
Linux环境下执行`./cli.js --help`命令时出现标题中的错误。通过vim打开后使用命令`:set ff=unix`更改文件格式后解决。

**Comment by vita-dounai** [comment]
Hi，在macOS Mojave 10.14.6下以及Ubuntu 18.04.3 LTS均没有复现出你的问题，能够给一下重现环境及步骤？谢谢！
