### ISSUE TITLE
sdk与节点的网络如果中断再去操作就会一直出错

### ISSUE THREAD

**Issue by slinzhang007** [FISCO-BCOS/nodejs-sdk#73]
sdk与节点的网络如果中断再去操作就会一直出错，即使网络恢复了，也会一直出错。 问题在于在channelPromise没有捕获tlsSocket.write的异常，并把异常的socket从sockets中剔除，最好在出现异常的时候做一次重连操作。

**Comment by vita-dounai** [comment]
非常感谢发现这个问题，这个的确是我们之前的测试没有覆盖到的情况。

现在的修复方案为：监听tlsSocket的error事件，当error发生时，清除此socket及相关缓存，并向上抛出异常，由上层应用决定是否发起重连，若重连则会初始化新的socket和缓存。
